# ==========================================
# ?? ?? ???? ??? ?? ??
# ==========================================

# 1. ????? ?? ?? ??
converter.hwp.exe.path=C:/Program Files (x86)/Hnc/Office 2018/HOffice100/Bin/Hwp.exe

# 2. ???? ?? ???? ?? (? ??)
converter.timeout.seconds=30