# ===================================================================
# [IPLMS Hybrid Converter Engine ?? ??]
# ===================================================================

# input folder
converter.input.dir=c:\\IPLMS\\91_input

# output folder
converter.output.dir=c:\\IPLMS\\92_output

# \uD30C\uC77C\uBCC0\uD658 thread \uC758 \uAC1C\uC218
converter.thread.count=4

# \uD30C\uC77C\uBCC0\uD658 timeout
converter.timeout.seconds=90

# Libreoffice \uC5D4\uC9C4\uC758 \uC2E4\uD589\uD30C\uC77C \uC704\uCE58
#converter.libreoffice.path=C:\\Program Files\\LibreOffice\\program\\soffice.exe
converter.libreoffice.path=c:\\IPLMS\\LibreOfficePortable\\LibreOfficePortable.exe

# \uBCC0\uD658\uACB0\uACFC \uC800\uC7A5 \uD30C\uC77C\uBA85
converter.report.excel.name=conversion_report.csv

# Daemon \uC2E4\uD589 \uC8FC\uAE30 (\uBD84)
daemon.interval.minutes=10

# \uB0B4\uC7A5 HTTP \uC11C\uBC84 \uD3EC\uD2B8 \uC124\uC815 (\uB2E8\uC77C \uD30C\uC77C \uC989\uC2DC \uBCC0\uD658\uC6A9 API)
converter.server.port=9119
